import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { siteConfig } from "@/config/site";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export const metadata: Metadata = {
  metadataBase: new URL('https://smartshipping.app/'),
  title: siteConfig.name,
  description: siteConfig.description,
  keywords: [
    "Smart Shipping",
    "Shopify shipping",
    "shipping optimization",
    "shipping rates",
    "automated fulfillment",
    "delivery management",
    "logistics automation",
    "ecommerce shipping",
    "shipping calculator",
    "courier integration"
  ],
  openGraph: {
    title: siteConfig.name,
    siteName: siteConfig.name,
    url: 'https://smartshipping.app',
    description: siteConfig.description,
    images: [
      {
        url: 'https://smartshipping.app/preview.png',
        alt: 'Smart Shipping App preview',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: siteConfig.name,
    images: [
      {
        url: 'https://smartshipping.app/preview.png',
        alt: 'Smart Shipping App preview',
      },
    ],
    description: siteConfig.description,
  },
  icons: [
    {
      rel: "icon",
      url: "/favicon.png",
      type: "image/png"
    },
    {
      rel: "apple-touch-icon",
      url: "/favicon.png",
      type: "image/png"
    }
  ]
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
